config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'layout#index'
    resources :articles, except: :show
    resources :courses, except: :show
    resources :tournaments
    resources :tutorials
  end

  resources :articles, only: [:index, :show] do
    resources :comentarios
  end
  resources :courses, only: [:index, :show]
  resources :tournaments, only: :index
  resources :tutorials, only: :index do
    member do
      put "upvote" => "tutorials#upvote"
      put "downvote" => "tutorials#downvote"
    end
  end


  root to: 'articles#index'
  get '/watch-twitch' => 'tournaments#watch'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  acts_as_votable
end

app/controllers/admin/tutorials_controller.rb
class Admin::TutorialsController < ApplicationController
  respond_to :html
  before_action :is_admin

  def index
    @tutorials = Tutorial.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @tutorial = Tutorial.find(params[:id])
  end

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = Tutorial.new(permited_params)
    if @tutorial.save
      flash[:notice] = "Noticia creada."
      redirect_to admin_tutorials_path
    else
      respond_with @tutorial
    end
  end

  def edit
    @tutorial = Tutorial.find(params[:id])
  end

  def update
    @tutorial = Tutorial.find(params[:id])
    if @tutorial.update(permited_params)
      flash[:notice] = "Noticia actualizada"
      redirect_to admin_tutorials_path
    else
      respond_with @tutorial
    end
  end

  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy
    redirect_to admin_tutorial_path
  end

  private
  def permited_params
    params.require(:tutorial).permit(:name, :url, :description, :language)
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def index
    @tutorials = Tutorial.all
  end

  def upvote
    @tutorial = Tutorial.find(params[:id])
    @tutorial.upvote_from current_user
    redirect_to :back
  end

  def downvote
    @tutorial = Tutorial.find(params[:id])
    @tutorial.downvote_from current_user
    redirect_to :back
  end
end

app/views/admin/tutorials/_form.html.erb
<%= simple_form_for [:admin, @tutorial] do |f| %>
  <%= f.input :name, label: "Nombre" %>
  <%= f.input :description, label: "Descripción",
              hint: "Algunos de los estilos pueden romper el estilo de la
                pagina, verifica que no sea así", :as => :ckeditor %>
  <%= f.input :url, label: "Enlace", hint: "El enlace debe contener protocolo http:// forzosamente! Ejemplo: http://www.google.com"%>
  <%= f.input :language, label: "Idioma" %>
  <%= f.submit %>
<% end %>

app/views/admin/tutorials/edit.html.erb
<h3> Editar recurso </h3>
<%= render 'form' %>

app/views/admin/tutorials/index.html.erb
<div class="tutorials-header">
  <h3>Tutoriales</h3>
  <%= link_to "Nuevo recurso", new_admin_tutorial_path,
    class: "btn btn-primary" %>
</div>
<div class="admin-tutorials">
  <% @tutorials.each do |tutorial| %>
    <div class="tutorial">
      <h4><%= tutorial.name %></h4>
      <p><%= raw(tutorial.description) %></p>
      <div class="language">
        <b> Idoma: </b><%= tutorial.language %>
        <b> Enclace: </b><%= tutorial.url %>
      </div>
      <div class="settings">
      <%= link_to [:admin, tutorial], method: :delete, data: { confirm: 'Borrar?' } do %>
        <span class="glyphicon glyphicon-trash"></span>
        Borrar
      <% end %>
        <%= link_to "Editar", edit_admin_tutorial_path(tutorial),
          class: "glyphicon glyphicon-edit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/tutorials/new.html.erb
<h3> Agregar recurso </h3>
<%= render 'form' %>