config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'layout#index'
    resources :articles, except: :show
    resources :courses, except: :show
    resources :tournaments
    resources :tutorials
  end

  resources :articles, only: [:index, :show] do
    resources :comentarios
  end
  resources :courses, only: [:index, :show]
  resources :tournaments, only: :index
  resources :tutorials, only: :index do
    member do
      put "upvote" => "tutorials#upvote"
      put "downvote" => "tutorials#downvote"
    end
  end


  root to: 'articles#index'
  get '/watch-twitch' => 'tournaments#watch'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :comentarios

  validates :title, :body, :image, presence: true
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  respond_to :html
  before_action :is_admin

  def index
    @articles = Article.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(permited_params)
    if @article.save
      flash[:notice] = "Noticia creada."
      redirect_to admin_articles_path
    else
      respond_with @article
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(permited_params)
      flash[:notice] = "Noticia actualizada"
      redirect_to admin_articles_path
    else
      respond_with @article
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end

  private
  def permited_params
    params.require(:article).permit(:title, :body, :author, :image)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html

  def index
    @articles = Article.all.order(created_at: :desc)
      .paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comentario.new
    @user = current_user
    @comments = @article.comentarios.all
  end

  private
  def permited_params
    params.require(:comentario).permit(:text)
  end
end

app/views/articles/_comments_form.html.erb
<div class="user">
  <%= image_tag current_user.profile_picture %>
  <b><%= current_user.first_name + " " + current_user.last_name %></b>
</div>
<%= simple_form_for @comment, :url => "/articles/#{@article.id}/comentarios",
  :method => :post do |o| %>
  <%= o.input :text, label: "Comentario" %>
  <%= o.hidden_field :user_id, value: @user.id  %>
  <%= o.submit %>
<% end %>

app/views/articles/_comments_index.html.erb
<div class="all-comments">
  <% @comments.each do |comment| %>
    <div class="comment">
      <div class="user">
        <%= image_tag comment.user.profile_picture %>
        <b><%= comment.user.first_name + " " + comment.user.last_name %></b>
        <br>
        <%= comment.created_at.strftime("%d %b. %Y - %r") %>
      </div>
      <p><%= comment.text %></p>
      <% if comment.user == current_user || current_admin %>
        <%= link_to article_comentario_path(@article.id, comment.id), method: :delete,
          data: { confirm: 'Borrar?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/articles/index.html.erb
<% content_for :title, "IDS Comite de Alumnos | Noticias" %>
<div class="news-header">
  <h3>Noticias</h3>
</div>
<div class="articles">
  <% @articles.each do |article| %>
    <div class="article">
      <h3><%= article.title %></h3>
      <div class="under-title">
        Redactado por: <%= article.author %>
        el <%= article.created_at.strftime('%F') %>
      </div>
      <div class="contenido">
        <div class="image">
          <%= image_tag article.image %>
        </div>
        <div class="texto">
          <%= raw (article.body.truncate(840)) %>
        </div>
      </div>
      <div class="more">
        <% if current_admin %>
          <%= link_to [:admin, article], method: :delete,
                                          data: { confirm: 'Borrar?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            Borrar
          <% end %>
            <%= link_to "Editar", edit_admin_article_path(article),
              class: "glyphicon glyphicon-edit" %>
        <% end %>
        <%= link_to "Leer más...", article_path(article) %>
      </div>
    </div>
  <% end %>
  <div class="center">
    <%= will_paginate @articles, :previous_label => 'Anterior', :next_label => 'Siguiente',  renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/articles/show.html.erb
<% content_for :title, "IDS Comite de Alumnos | #{@article.title}" %>
<div class="article">
  <h3><%= @article.title %></h3>
  <div class="under-title">
    Redactado por: <%= @article.author %>
    el <%= @article.created_at.strftime('%F') %>
  </div>
  <div class="contenido">
    <div class="image">
      <%= image_tag @article.image %>
    </div>
    <div class="texto">
      <%= raw(@article.body) %>
    </div>
  </div>
  <div class="social">
    <div class="fb-like" data-layout="standard" data-action="like" data-show-faces="true" data-share="true">
    </div>
  </div>
</div>

<div class="comments">
  <% if current_user %>
    <div class="new-comment">
      <%= render 'comments_form' %>
    </div>
  <% else %>
    <div class="no-session">
      <h1>Inicia sesión con <%= link_to "Facebook", "/auth/facebook" %> para comentar!<h1>
    </div>
  <% end %>

  <%= render 'comments_index' %>

</div>