config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'layout#index'
    resources :articles, except: :show
    resources :courses, except: :show
    resources :tournaments
    resources :tutorials
  end

  resources :articles, only: [:index, :show] do
    resources :comentarios
  end
  resources :courses, only: [:index, :show]
  resources :tournaments, only: :index
  resources :tutorials, only: :index do
    member do
      put "upvote" => "tutorials#upvote"
      put "downvote" => "tutorials#downvote"
    end
  end


  root to: 'articles#index'
  get '/watch-twitch' => 'tournaments#watch'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  acts_as_votable
end

app/controllers/admin/tutorials_controller.rb
class Admin::TutorialsController < ApplicationController
  respond_to :html
  before_action :is_admin

  def index
    @tutorials = Tutorial.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @tutorial = Tutorial.find(params[:id])
  end

  def new
    @tutorial = Tutorial.new
  end

  def create
    @tutorial = Tutorial.new(permited_params)
    if @tutorial.save
      flash[:notice] = "Noticia creada."
      redirect_to admin_tutorials_path
    else
      respond_with @tutorial
    end
  end

  def edit
    @tutorial = Tutorial.find(params[:id])
  end

  def update
    @tutorial = Tutorial.find(params[:id])
    if @tutorial.update(permited_params)
      flash[:notice] = "Noticia actualizada"
      redirect_to admin_tutorials_path
    else
      respond_with @tutorial
    end
  end

  def destroy
    @tutorial = Tutorial.find(params[:id])
    @tutorial.destroy
    redirect_to admin_tutorial_path
  end

  private
  def permited_params
    params.require(:tutorial).permit(:name, :url, :description, :language)
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def index
    @tutorials = Tutorial.all
  end

  def upvote
    @tutorial = Tutorial.find(params[:id])
    @tutorial.upvote_from current_user
    redirect_to :back
  end

  def downvote
    @tutorial = Tutorial.find(params[:id])
    @tutorial.downvote_from current_user
    redirect_to :back
  end
end

app/views/tutorials/index.html.erb
<% content_for :title, "IDS Comite de Alumnos | Tutoriales" %>

<div class="tutorials-header">
  <h3>Tutoriales</h3>
</div>
<div class="tutorials">

  <% @tutorials.each do |tutorial| %>
    <div class="tutorial">
      <div class="main">
        <h3><%= tutorial.name %></h3>
        <p><%= raw(tutorial.description) %></p>
        <div class="language">
          <b> Idioma: </b><%= tutorial.language %> <br>
           <b> Enclace: </b><%= link_to tutorial.url, tutorial.url %>
        </div>
      </div>
      <div class="more">
        <div class="votes">
          <%= tutorial.get_upvotes.size - tutorial.get_downvotes.size%>
        </div>
        <div class="thumbs">
          <%= button_to upvote_tutorial_path(tutorial),
            class: "like btn btn-default", method: :put do %>
              <span class="glyphicon glyphicon-thumbs-up"></span>
          <% end %>
          <%= button_to downvote_tutorial_path(tutorial),
            class: "dislike btn btn-default", method: :put do %>
            <span class="glyphicon glyphicon-thumbs-down"></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>