config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    root to: 'layout#index'
    resources :articles, except: :show
    resources :courses, except: :show
    resources :tournaments
    resources :tutorials
  end

  resources :articles, only: [:index, :show] do
    resources :comentarios
  end
  resources :courses, only: [:index, :show]
  resources :tournaments, only: :index
  resources :tutorials, only: :index do
    member do
      put "upvote" => "tutorials#upvote"
      put "downvote" => "tutorials#downvote"
    end
  end


  root to: 'articles#index'
  get '/watch-twitch' => 'tournaments#watch'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
end

app/models/article.rb
class Article < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :comentarios

  validates :title, :body, :image, presence: true
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
  validates :text, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
  mount_uploader :image, ImageUploader
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :players
  belongs_to :tournament
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  has_many :teams, dependent: :destroy
end

app/models/tutorial.rb
class Tutorial < ActiveRecord::Base
  acts_as_votable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  acts_as_voter
  has_many :comentarios

  def logged_with_facebook?
    self.facebook_id.present?
  end

  def update_facebook_info(auth)
    create_pass
    update(
        facebook_id: auth["uid"],
        first_name: auth["info"]["name"].split(' ').first,
        last_name: auth["info"]["name"].split(' ').last,
        password: @temp_pass,
        password_confirmation: @temp_pass
      )
  end

  def profile_picture
    "https://graph.facebook.com/#{self.facebook_id}/picture?width=100&height=100"
  end

  private
  def create_pass
    @temp_pass = (0...8).map { (65 + rand(26)).chr }.join
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  respond_to :html
  before_action :is_admin

  def index
    @articles = Article.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(permited_params)
    if @article.save
      flash[:notice] = "Noticia creada."
      redirect_to admin_articles_path
    else
      respond_with @article
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(permited_params)
      flash[:notice] = "Noticia actualizada"
      redirect_to admin_articles_path
    else
      respond_with @article
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end

  private
  def permited_params
    params.require(:article).permit(:title, :body, :author, :image)
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  respond_to :html
  before_action :is_admin

  def index
    @courses = Course.all.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
    course_status
  end

  def create
    @course = Course.new(permited_params)
    if @course.save
      flash[:notice] = "Curso creado."
      redirect_to admin_courses_path
    else
      respond_with @course
    end
  end

  def edit
    @course = Course.find(params[:id])
    course_status
  end

  def update
    @course = Course.find(params[:id])
    if @course.update(permited_params)
      flash[:notice] = "Curso actualizado."
      redirect_to admin_courses_path
    else
      respond_with @course
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to admin_courses_path
  end

  private
  def permited_params
    params.require(:course).permit(:name, :description, :image, :start_date,
      :finish_date, :status)
  end
  def course_status
    @course_status = [ "Inscripciones abiertas", "Inscripciones cerradas",
      "Finalizado" ]
  end
end

app/controllers/admin/layout_controller.rb
class Admin::LayoutController < ApplicationController
  before_action :is_admin, except: :search

  def index
    params[:search] = "" if params[:search].nil?
    unless params[:search].empty?
      @users = User.where("first_name like ? or last_name like ?",
        '%'+ params[:search] + '%',
        '%' + params[:search] + '%').paginate(:page => params[:page],
                                                      :per_page => 10)
      if @users.count < 1
        flash.now[:danger] = 'Nothing found'
        @users = User.all.paginate(:page => params[:page],
                                             :per_page => 10)
      end
    else
      @users = User.all.paginate(:page => params[:page],
                                             :per_page => 10)
    end
    @users
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :is_admin, :current_admin
  include SessionsHelper

  def current_admin
    current_user.admin if session[:user_id]
  end

  def is_admin
    if  current_user.nil? || !current_admin
      flash[:error] = "No haz iniciado sesión o no eres administrador."
      redirect_to root_path
    end
  end



end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  respond_to :html

  def index
    @articles = Article.all.order(created_at: :desc)
      .paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @article = Article.find(params[:id])
    @comment = Comentario.new
    @user = current_user
    @comments = @article.comentarios.all
  end

  private
  def permited_params
    params.require(:comentario).permit(:text)
  end
end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  respond_to :html
  helper_method :user
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comentarios.create(permited_params)
    if @comment.save
      redirect_to :back
    else
      respond_with @article
    end
  end

  def destroy
    @comment = Comentario.find(params[:id])
    @comment.destroy
    redirect_to :back
  end

  private
  def permited_params
    params.require(:comentario).permit(:text, :user_id)
  end

  def user
    @user = current_user
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    if params[:provider].present?
      auth = request.env["omniauth.auth"]
      user = User.find_by_facebook_id(auth["uid"]) ||
        User.new
      user.update_facebook_info(auth)
      session[:user_id] = user.id
      redirect_to :back
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  def index
    @tournaments = Tournament.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 10)
  end

  def watch
  end
end

app/controllers/tutorials_controller.rb
class TutorialsController < ApplicationController
  def index
    @tutorials = Tutorial.all
  end

  def upvote
    @tutorial = Tutorial.find(params[:id])
    @tutorial.upvote_from current_user
    redirect_to :back
  end

  def downvote
    @tutorial = Tutorial.find(params[:id])
    @tutorial.downvote_from current_user
    redirect_to :back
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def log_in
    session[:user_id] = @object.id
  end

  def logged_in?
    !current_user.nil?
  end
end

app/views/admin/layout/_search.html.erb
<%= form_tag admin_root_path, :method => 'get' do %>
  <div class="input-group">
    <%= text_field_tag :search, nil, placeholder: "Buscar usuarios...",
      class: "form-control" %>
    <%= submit_tag "Search", class: "btn btn-default srch-btn" %>
  </div>
<% end %>

app/views/admin/layout/_usersindex.html.erb
<div class="index">
  <table class = "table">
    <thead>
      <tr>
      <th></th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Admin</th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tbody>
        <td style="text-align:center"> <%= image_tag user.profile_picture %> </td>
        <td> <%= user.first_name %></td>
        <td> <%= user.last_name %> </td>
        <td> <%= user.admin %> </td>
      </tbody>
    <% end %>
  </table>
</div>

app/views/admin/layout/index.html.erb
<div class="admin-index">
<h3> Panel de Administración </h3>
  <div class="position">
    <%= link_to "Noticias", admin_articles_path %>
    <%= link_to "Cursos", admin_courses_path %>
    <%= link_to "Torneos", admin_tournaments_path %>
    <%= link_to "Tutoriales", admin_tutorials_path %>
  </div>
<div class="search">
  <%= render 'search' %>
</div>

<%= render 'usersindex' %>
<div class="center">
  <%= will_paginate @users,  renderer: BootstrapPagination::Rails %>
</div>

app/views/layouts/_googlead.html.erb
<div class="googlead">
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- IDSAlumnos -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-5517686570657210"
       data-ad-slot="2772564081"
       data-ad-format="auto"></ins>
  <script>
  (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="mobile-nav">
    <%= render 'layouts/navigation_links' %>
</div>
<div class="position">
  <div class="logo">
    <h4>IDS</h4>
    <span class="underlogo">Comite de Alumnos</span>
  </div>

  <div class="site-nav">
      <%= render 'layouts/navigation_links' %>
  </div>


  <div class="mobile-icon-toggle">
    <%= link_to "", "#", class: "glyphicon glyphicon-menu-hamburger",
                            id: "mobile-toggle"%>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<ul>
  <li><%= link_to "Inicio", root_path %></li>
  <li><%= link_to "Cursos", courses_path %></li>
  <li><%= link_to "Torneos", tournaments_path %></li>
  <li><%= link_to "Tutoriales", tutorials_path %></li>
  <li><%= link_to "+Facebook", "https://www.facebook.com/IDSUTM", target: '_blank' %></li>
</ul>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "IDS Comite de Alumnos" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Sociedad de Alumnos IDS" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="home-wrap">
      <header>
        <%= render 'layouts/navigation' %>
      </header>
      <main role="contents">
        <%= render 'layouts/messages' %>
        <%= render 'sessions/login' %>
        <%= yield %>
        <%= render 'layouts/googlead' %>
      </main>
    </div>
  </body>
</html>